#!/usr/bin/env python3.4
from collections import OrderedDict
import urllib.request


def getquote(symbol):

    url = "http://www.finance.yahoo.com/d/quotes?s=" + symbol
    + "&f=aa2a5bb2b3b4b6cc1c3c6c8dd1d2ee1e7e8e9f6ghjkg1g3g4g5g6ii5j1j3j4j5j6k1k2k"
    + "3k4k5ll1l2l3mm2m3m4m5m6m7m8nn4opp1p2p5p6qrr1r2r5r6r7ss1s7t1t6t7t8vv1v7ww1w4xy"
    ans = urllib.request.urlopen(url)
    ans = ans.read().decode('utf-8')
    L = ans.split(',')

    D = OrderedDict()
    D['ask'] = L[0]
    D['averagedailyvolume'] = L[1]
    D['asksize'] = L[2]
    D['bid'] = L[3]
    D['ask(realtime)'] = L[4]
    D['bid(realtime)'] = L[5]
    D['bookvalue'] = L[6]
    D['bidsize'] = L[7]
    D['changeand%change'] = L[8]
    D['change'] = L[9]
    D['commission'] = L[10]
    D['change(realtime)'] = L[11]
    D['afterhourschange(realtime)'] = L[12]
    D['dividend/share'] = L[13]
    D['lasttradedate'] = L[14]
    D['tradedate'] = L[15]
    D['earning/share'] = L[16]
    D['Errorindicator'] = L[17]
    D['eps(thisyear)'] = L[18]
    D['eps(nextyear)'] = L[19]
    D['eps(nextquarter)'] = L[20]
    D['floatshares'] = L[21]
    D['daylow'] = L[22]
    D['dayhigh'] = L[23]
    D['52weeklow'] = L[24]
    D['52weekhigh'] = L[25]
    D['holdingsgainpercent'] = L[26]
    D['annualizedgain'] = L[27]
    D['holdingsgain'] = L[28]
    D['holdingsgainpercent(realtime)'] = L[29]
    D['HoldingsGain(Real-time)'] = L[30]
    D['MoreInfo'] = L[31]
    D['OrderBook(Real-time)'] = L[32]
    D['MarketCapitalization'] = L[33]
    D['MarketCap(Real-time)'] = L[34]
    D['EBITDA'] = L[35]
    D['ChangeFrom52-weekLow'] = L[36]
    D['PercentChangeFrom52-weekLow'] = L[37]
    D['LastTrade(Real-time)WithTime'] = L[38]
    D['ChangePercent(Real-time)'] = L[39]
    D['LastTradeSize'] = L[40]
    D['ChangeFrom52-weekHigh'] = L[41]
    D['PercebtChangeFrom52-weekHigh'] = L[42]
    D['LastTrade(WithTime)'] = L[43]
    D['LastTrade(PriceOnly)'] = L[44]
    D['HighLimit'] = L[45]
    D['LowLimit'] = L[46]
    D['Day’sRange'] = L[47]
    D['Day’sRange(Real-time)'] = L[48]
    D['50-dayMovingAverage'] = L[49]
    D['200-dayMovingAverage'] = L[50]
    D['ChangeFrom200-dayMovingAverage'] = L[51]
    D['PercentChangeFrom200-dayMovingAverage'] = L[52]
    D['ChangeFrom50-dayMovingAverage'] = L[53]
    D['PercentChangeFrom50-dayMovingAverage'] = L[54]
    D['Name'] = L[55]
    D['Notes'] = L[56]
    D['Open'] = L[57]
    D['PreviousClose'] = L[58]
    D['PricePaid'] = L[59]
    D['ChangeinPercent'] = L[60]
    D['Price/Sales'] = L[61]
    D['Price/Book'] = L[62]
    D['Ex-DividendDate'] = L[63]
    D['P/ERatio'] = L[64]
    D['DividendPayDate'] = L[65]
    D['P/ERatio(Real-time)'] = L[66]
    D['PEGRatio'] = L[67]
    D['Price/EPSEstimateCurrentYear'] = L[68]
    D['Price/EPSEstimateNextYear'] = L[69]
    D['Symbol'] = L[70]
    D['SharesOwned'] = L[71]
    D['ShortRatio'] = L[72]
    D['LastTradeTime'] = L[73]
    D['TradeLinks'] = L[74]
    D['TickerTrend'] = L[75]
    D['1yrTargetPrice'] = L[76]
    D['Volume'] = L[77]
    D['HoldingsValue'] = L[78]
    D['HoldingsValue(Real-time)'] = L[79]
    D['52-weekRange'] = L[80]
    D['Day’sValueChange'] = L[81]
    D['Day’sValueChange(Real-time)'] = L[82]
    D['StockExchange'] = L[83]
    D['DividendYield'] = L[84]
    for i, k, v in enumerate(D.items()):
        print("{} {:<60} {}".format(i, k, v))
